[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Jim Blandy <jimb@red-bean.com>"]
build = "build.rs"
categories = ["development-tools::debugging", "development-tools::ffi"]
description = "A crate for demangling C++ symbols"
documentation = "https://docs.rs/cpp_demangle"
keywords = ["demangle", "symbolicate", "c-plus-plus", "itanium"]
license = "Apache-2.0/MIT"
name = "cpp_demangle"
readme = "./README.md"
repository = "https://github.com/fitzgen/cpp_demangle"
version = "0.2.1"

[badges]

[badges.travis-ci]
repository = "fitzgen/cpp_demangle"

[dependencies]
clap = "2.20.5"
fixedbitset = "0.1.5"

[dependencies.afl]
optional = true
version = "0.1.5"

[dependencies.afl-plugin]
optional = true
version = "0.1.5"

[dev-dependencies]
diff = "0.1.10"

[features]
fuzz = ["afl", "afl-plugin"]
logging = []
nightly = []
run_libiberty_tests = []

[profile]

[profile.release]
debug = true
