[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Jim Blandy <jimb@red-bean.com>"]
description = "A crate for demangling C++ symbols"
documentation = "https://docs.rs/cpp_demangle"
keywords = ["demangle", "symbolicate", "c-plus-plus", "itanium"]
license = "Apache-2.0/MIT"
name = "cpp_demangle"
readme = "./README.md"
repository = "https://github.com/fitzgen/cpp_demangle"
version = "0.1.0"

[dependencies]
error-chain = "0.7.1"

[features]
logging = []
nightly = []
