[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Jim Blandy <jimb@red-bean.com>"]
categories = ["development-tools::debugging", "development-tools::ffi"]
description = "A crate for demangling C++ symbols"
documentation = "https://docs.rs/cpp_demangle"
keywords = ["demangle", "symbolicate", "c-plus-plus", "itanium"]
license = "Apache-2.0/MIT"
name = "cpp_demangle"
readme = "./README.md"
repository = "https://github.com/fitzgen/cpp_demangle"
version = "0.1.0"

[badges]
travis-ci = { repository = "fitzgen/cpp_demangle" }

[dependencies]
fixedbitset = "0.1.5"

[dependencies.afl]
optional = true
version = "0.1.5"

[dependencies.afl-plugin]
optional = true
version = "0.1.5"

[features]
fuzz = ["afl", "afl-plugin"]
logging = []
nightly = []

[profile]

[profile.release]
debug = true
